In [2]:
import torch
import torch.nn as nn

# シンプルなRNNを定義する
rnn = nn.RNN(
    input_size=4,   # 各単語のベクトルの次元数
    hidden_size=8,  # 隠れ状態の次元数
    batch_first=True  # 入力の形を(バッチ, 系列長, 特徴量)にする
)

# 3単語・各4次元のダミー入力（1文章分）
x = torch.randn(1, 3, 4)
print("入力の形:", x.shape)
print("入力:\n", x)

# RNNに通す
output, hidden = rnn(x)
print("出力の形:", output.shape)
print("隠れ状態の形:", hidden.shape)

入力の形: torch.Size([1, 3, 4])
入力:
 tensor([[[ 0.2043, -0.4371,  0.8875, -0.6892],
         [-0.0780, -0.3633,  0.6904,  0.7516],
         [ 1.6706,  0.1691,  0.5978, -0.7869]]])
出力の形: torch.Size([1, 3, 8])
隠れ状態の形: torch.Size([1, 1, 8])


In [3]:
# 長い文章でRNNがどうなるか確認する
rnn_long = nn.RNN(input_size=4, hidden_size=8, batch_first=True)

# 50単語の長い文章
x_long = torch.randn(1, 50, 4)
output_long, hidden_long = rnn_long(x_long)

# 最初と最後の隠れ状態の値を比較する
print("最初のステップの出力（1単語目の情報）:")
print(output_long[0, 0, :].detach().round(decimals=3))

print("\n最後のステップの出力（50単語目、全体の記憶）:")
print(output_long[0, -1, :].detach().round(decimals=3))

# 1単語目の情報がどれだけ残っているか
first = output_long[0, 0, :].detach()
last = output_long[0, -1, :].detach()
similarity = torch.dot(first, last) / (torch.norm(first) * torch.norm(last))
print("\n1単語目と最後の隠れ状態のコサイン類似度:", similarity.item())

最初のステップの出力（1単語目の情報）:
tensor([-0.5220,  0.2640,  0.1200, -0.2410,  0.0040, -0.5570,  0.4910,  0.0050])

最後のステップの出力（50単語目、全体の記憶）:
tensor([-0.7740,  0.7450, -0.1600,  0.1750, -0.1170, -0.8260,  0.6410, -0.2230])

1単語目と最後の隠れ状態のコサイン類似度: 0.8676464557647705


In [4]:
# RNNをLSTMに変えるだけ
lstm = nn.LSTM(input_size=4, hidden_size=8, batch_first=True)

x = torch.randn(1, 3, 4)
output, (hidden, cell) = lstm(x)  # hiddenに加えてcellが増えた

print("出力の形:", output.shape)
print("隠れ状態の形:", hidden.shape)
print("セル状態の形:", cell.shape)

出力の形: torch.Size([1, 3, 8])
隠れ状態の形: torch.Size([1, 1, 8])
セル状態の形: torch.Size([1, 1, 8])
