In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
corpus = [
    "私は犬が好き",
    "私は猫が好き",
    "犬も猫も好き",
]

# 文字単位でBoWを作成（analyzer="char"の意味は後で説明）
vectorizer = CountVectorizer(analyzer="char")
X = vectorizer.fit_transform(corpus)

print("単語一覧:", vectorizer.get_feature_names_out())
print("\n行列:\n", X.toarray())

単語一覧: ['が' 'き' 'は' 'も' '好' '犬' '猫' '私']

行列:
 [[1 1 1 0 1 1 0 1]
 [1 1 1 0 1 0 1 1]
 [0 1 0 2 1 1 1 0]]


In [3]:
# 英語ならスペース区切りで自然に単語分割できる
corpus_en = [
    "I like dogs",
    "I like cats",
    "dogs and cats",
]

vectorizer_en = CountVectorizer()  # デフォルトはスペース区切り
X_en = vectorizer_en.fit_transform(corpus_en)

print("単語一覧:", vectorizer_en.get_feature_names_out())
print("\n行列:\n", X_en.toarray())

単語一覧: ['and' 'cats' 'dogs' 'like']

行列:
 [[0 0 1 1]
 [0 1 0 1]
 [1 1 1 0]]


In [4]:
# BoWの問題点を見る
corpus2 = [
    "犬が好き 犬は かわいい 犬を 飼いたい",
    "猫が好き 猫は かわいい",
    "犬も 猫も かわいい",
]

vectorizer2 = CountVectorizer(analyzer="char")
X2 = vectorizer2.fit_transform(corpus2)

print("単語一覧:", vectorizer2.get_feature_names_out())
print("\n行列:\n", X2.toarray())

単語一覧: [' ' 'い' 'か' 'が' 'き' 'た' 'は' 'も' 'わ' 'を' '好' '犬' '猫' '飼']

行列:
 [[4 4 1 1 1 1 1 0 1 1 1 3 0 1]
 [2 2 1 1 1 0 1 0 1 0 1 0 2 0]
 [2 2 1 0 0 0 0 2 1 0 0 1 1 0]]


TF  = その単語がその文書に何回出てくるか（多いほど重要）
IDF = その単語が全文書のうち何割に出てくるか（少ない文書にしか出ない単語ほど重要）

TF-IDF = TF × IDF

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer

# スペース区切りの英語で試す（日本語は後でちゃんとやる）
corpus_en2 = [
    "I like dogs dogs dogs",  # dogsが3回
    "I like cats",
    "dogs and cats are cute",
]

tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(corpus_en2)

print("単語一覧:", tfidf.get_feature_names_out())
print("\n行列(小数第2位まで):\n", X_tfidf.toarray().round(2))

単語一覧: ['and' 'are' 'cats' 'cute' 'dogs' 'like']

行列(小数第2位まで):
 [[0.   0.   0.   0.   0.95 0.32]
 [0.   0.   0.71 0.   0.   0.71]
 [0.49 0.49 0.37 0.49 0.37 0.  ]]


In [6]:
corpus = [
    "I like dogs dogs dogs",
    "I like cats",
    "dogs and cats are cute",
]

vectorizer = CountVectorizer()

# fitとtransformを分けてやってみる
vectorizer.fit(corpus)
print("単語一覧:", vectorizer.get_feature_names_out())

X = vectorizer.transform(corpus)
print("\n疎行列:\n", X)
print("\nNumPy配列:\n", X.toarray())

単語一覧: ['and' 'are' 'cats' 'cute' 'dogs' 'like']

疎行列:
 <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 9 stored elements and shape (3, 6)>
  Coords	Values
  (0, 4)	3
  (0, 5)	1
  (1, 2)	1
  (1, 5)	1
  (2, 0)	1
  (2, 1)	1
  (2, 2)	1
  (2, 3)	1
  (2, 4)	1

NumPy配列:
 [[0 0 0 0 3 1]
 [0 0 1 0 0 1]
 [1 1 1 1 1 0]]
